# librerie principali
require File.expand_path('lib/main')
# script di terzi
require File.expand_path('lib/3rd_party/yem_aggro')
require File.expand_path('lib/3rd_party/tankentai')
require File.expand_path('lib/3rd_party/turn_skills')
require File.expand_path('lib/3rd_party/y6_engine')
require File.expand_path('lib/3rd_party/kgc_largeparty')
# script miei
require File.expand_path('script_updater')
require File.expand_path('controller')
require File.expand_path('key_shower')
require File.expand_path('window_key_help')
require File.expand_path('Localization')
require File.expand_path('system.rb')
require File.expand_path('element_attack')
require File.expand_path('sinergia')
require File.expand_path('support_windows')
require File.expand_path('PlayerInfo')
require File.expand_path('DialogWindow')
require File.expand_path('Options')
require File.expand_path('Face_Cache.rb')
require File.expand_path('window_emoji')
require File.expand_path('equip_enchant')
require File.expand_path('yem_equip')
require File.expand_path('yem_skill')
require File.expand_path('window_enanchement')
require File.expand_path('EnhancedSprite')
require File.expand_path('smooth_movements')
require File.expand_path('bitmap')
require File.expand_path('Attributi')
require File.expand_path('item_rarity')
require File.expand_path('battle_hud')
require File.expand_path('scene_item')
require File.expand_path('item_expand')
require File.expand_path('new_equip')
require File.expand_path('achievements')
require File.expand_path('controller')
require File.expand_path('bestiary')
require File.expand_path('scene_status')
require File.expand_path('espers_core')
require File.expand_path('forge')
require File.expand_path('alchemy')

